### ISSUE TITLE
Permission Denied (publickey)

### ISSUE THREAD

**Issue by joshlsullivan** [divio/divio-cli#172]
I've installed divio-cli, but I get this error:

Creating workspace
cloning project repository
Cloning into '/Users/joshsullivan/Documents/Divio/grace-reformed-church'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
There was an error trying to run a command. This is most likely
not an issue with divio-cli, but the called program itself.
Try checking the output of the command above.
The command was:
git clone git@git.divio.com:grace-reformed-church.git /Users/joshsullivan/Documents/Divio/grace-reformed-church

I made sure the SSH keys were setup correctly. Another other steps I can take?

**Comment by Chive** [comment]
Hi Josh

We just had an issue with updating our git authentication endpoint, which has now been fixed. Could you please try again?

Best,
Kim

**Comment by hmhrex** [comment]
I'm actually experiencing the same issue. I've even generated a new SSH key according to your guides and for some reason I'm still being denied. Is there still something wrong with git authentication?
