### ISSUE TITLE
Incorrect exit code on deploy failure

### ISSUE THREAD

**Issue by vxsx** [divio/divio-cli#205]
divio project deploy exits with a success exit code when the deployment fails

**Comment by chescales** [comment]
Hi @vxsx I tried two different failures during deployment, and on both cases the error code is 1. Could you please give some more details into how to reproduce the deployment error with code 0?

Here are the two tests I tried:

```
$ divio project deploy
Deploying test server
  [#-----------------------------------]    3%  Waiting for a free worker (1 second ago)
Traceback (most recent call last):
  ...
RuntimeError: TEST

$ echo $?
1
```

```
$ divio project deploy
Already deploying test server, attaching to running deployment
  [################################----]   90%  error                                
Error: 
Deployment failed. Please run 'divio project deploy-log test' to get more informaton

$ echo $?
1
```

**Comment by vxsx** [comment]
not really, at this point i don't remember what the project was and what were the conditions. I think it's safe to close it for now and reopen if I manage to reproduce

thanks for looking into it!
