### ISSUE TITLE
Latest released version on PyPI is not merged into master

### ISSUE THREAD

**Issue by vinitkumar** [divio/divio-cli#235]
Hey guys!

I was trying to find the latest release of Divio-CLI  (v3.7.0) that is released into PyPI in the code. It seems like that the code is never merged into master.  I think it should be as the standard practice of git project is to release after merging something into master. The repository looks out of sync. Even the releases are not tagged properly. it seems.

<img width="818" alt="Screenshot 2020-07-03 at 9 18 18 AM" src="https://user-images.githubusercontent.com/537678/86429813-397e6d00-bd0e-11ea-985b-bd9c1f9afc7c.png">
<img width="1243" alt="Screenshot 2020-07-03 at 9 18 36 AM" src="https://user-images.githubusercontent.com/537678/86429815-3c795d80-bd0e-11ea-8855-707658b13165.png">

**Comment by kinkerl** [comment]
the git sync broke and this repository was not updated with the latest information. sync is fixed and the code and tags are now available again.
